# https://github.com/marketplace/actions/go-release-binaries
name: Release CI

on:
  release:
    types: [created]

jobs:
  release-builds:
    name: release linux/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux,windows,darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v6
    - uses: wangyoucao577/go-release-action@v1.55
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goversion: "https://dl.google.com/go/go1.25.7.linux-amd64.tar.gz"
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: storagecheck
        retry: 10
        sha256sum: true
        overwrite: true
        pre_command: go mod tidy
