name: Container
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
      - end2end
    tags:        
      - '*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Login Build Push
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          export DOCKER_BUILDKIT=1
          docker build -f Dockerfile -t ghcr.io/${{ github.repository_owner }}/${IMAGE}/${IMAGE}:${VERSION} .
          docker push ghcr.io/${{ github.repository_owner }}/${IMAGE}/${IMAGE}:${VERSION}
          docker tagghcr.io/${{ github.repository_owner }}/${IMAGE}/${IMAGE}:${VERSION} ghcr.io/${{ github.repository_owner }}/${IMAGE}/${IMAGE}:latest
          docker push ghcr.io/${{ github.repository_owner }}/${IMAGE}/${IMAGE}:latest
        env:
          IMAGE: storagecheck
